# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1


before_script:
- apt-get update -yqq
- docker-php-ext-install mbstring mcrypt pdo_pgsql curl json intl gd xml zip bz2 opcache
- pecl install xdebug
- docker-php-ext-enable xdebug
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
#test:
#  script:
#  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  
deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash data/deploy.sh